spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#  autoconfigure:
#    exclude:org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration